/**
 * Comandos de consola ASA (UE5) usados en PvP / FPS.
 * Off = valor típico para quitar / bajar. On = valor para dejarlo puesto / default.
 * Los `show` son toggle: si lo tiras dos veces se deshace.
 */
const GROUPS = [
  { id: "cielo", name: "Cielo y niebla" },
  { id: "sombras", name: "Sombras" },
  { id: "lumen", name: "Lumen y cuevas" },
  { id: "hierba", name: "Hierba y plantas" },
  { id: "agua", name: "Agua" },
  { id: "post", name: "Postproceso" },
  { id: "fps", name: "FPS y resolución" },
  { id: "texturas", name: "Texturas y meshes" },
  { id: "fx", name: "Partículas y FX" },
  { id: "show", name: "Show (toggle)" },
  { id: "camara", name: "Cámara y UI" },
  { id: "debug", name: "Debug" },
];

const COMMANDS = [
  {
    group: "cielo",
    name: "Nubes volumétricas",
    off: "r.VolumetricCloud 0",
    on: "r.VolumetricCloud 1",
    quita: "Quita las nubes 3D. Más FPS y cielo limpio.",
    pone: "Pone nubes volumétricas (bonitas, caras).",
  },
  {
    group: "cielo",
    name: "Niebla volumétrica",
    off: "r.VolumetricFog 0",
    on: "r.VolumetricFog 1",
    quita: "Quita niebla espesa (cuevas/valle más legibles).",
    pone: "Pone niebla volumétrica.",
  },
  {
    group: "cielo",
    name: "Fog de distancia",
    off: "r.Fog 0",
    on: "r.Fog 1",
    quita: "Quita la niebla de horizonte. Más visibilidad larga.",
    pone: "Pone fog de distancia (el mapa se desvanece lejos).",
  },
  {
    group: "cielo",
    name: "Sky atmosphere",
    off: "r.SkyAtmosphere 0",
    on: "r.SkyAtmosphere 1",
    quita: "Quita atmósfera del cielo (cielo plano, un poco más FPS).",
    pone: "Pone cielo/atmósfera normal.",
  },
  {
    group: "cielo",
    name: "Light shafts (rayos de sol)",
    off: "r.LightShaftQuality 0 | r.LightShafts 0",
    on: "r.LightShaftQuality 1 | r.LightShafts 1",
    quita: "Quita rayos de sol / god rays.",
    pone: "Pone rayos de sol.",
  },
  {
    group: "cielo",
    name: "Intensidad skylight",
    off: "r.SkylightIntensityMultiplier 3",
    on: "r.SkylightIntensityMultiplier 1",
    quita: "Sube luz de cielo (escena más clara, a veces plana).",
    pone: "Luz de cielo normal (1).",
  },
  {
    group: "sombras",
    name: "Calidad de sombras",
    off: "r.ShadowQuality 0",
    on: "r.ShadowQuality 3",
    quita: "Quita / tira al mínimo las sombras dinámicas. Mucho FPS.",
    pone: "Sombras altas.",
  },
  {
    group: "sombras",
    name: "Virtual shadow maps",
    off: "r.Shadow.Virtual.Enable 0",
    on: "r.Shadow.Virtual.Enable 1",
    quita: "Quita VSM (carísimo en ASA). Recomendado off en PvP.",
    pone: "Activa sombras virtuales UE5.",
  },
  {
    group: "sombras",
    name: "Cascadas CSM",
    off: "r.Shadow.CSM.MaxCascades 0",
    on: "r.Shadow.CSM.MaxCascades 4",
    quita: "Quita cascadas de sombras direccionales.",
    pone: "Pone cascadas (sombras de sol a más distancia).",
  },
  {
    group: "sombras",
    name: "Contact shadows",
    off: "r.ContactShadows 0",
    on: "r.ContactShadows 1",
    quita: "Quita sombras de contacto (detalles pegados al suelo).",
    pone: "Pone contact shadows.",
  },
  {
    group: "sombras",
    name: "Distance field shadows",
    off: "r.DistanceFieldShadowing 0",
    on: "r.DistanceFieldShadowing 1",
    quita: "Quita sombras de distance field.",
    pone: "Pone DFS.",
  },
  {
    group: "sombras",
    name: "Escala distancia sombra",
    off: "r.Shadow.DistanceScale 0.1",
    on: "r.Shadow.DistanceScale 1",
    quita: "Acorta mucho hasta dónde se dibujan sombras.",
    pone: "Distancia de sombras normal.",
  },
  {
    group: "sombras",
    name: "Resolución máxima sombra",
    off: "r.Shadow.MaxResolution 0",
    on: "r.Shadow.MaxResolution 2048",
    quita: "Baja/anula resolución de mapas de sombra.",
    pone: "Sombras nítidas (caro).",
  },
  {
    group: "lumen",
    name: "Método GI (cuevas)",
    off: "r.DynamicGlobalIlluminationMethod 0",
    on: "r.DynamicGlobalIlluminationMethod 1",
    quita: "Apaga GI. Cuevas negras. No lo uses si quieres ver dentro.",
    pone: "Lumen ON. Cuevas claras. Pon 1 para ver cuevas.",
  },
  {
    group: "lumen",
    name: "Lumen indirecto (cuevas)",
    off: "r.Lumen.DiffuseIndirect.Allow 0",
    on: "r.Lumen.DiffuseIndirect.Allow 1",
    quita: "Apaga luz indirecta Lumen → cuevas negras.",
    pone: "Deja Lumen indirecto. Necesario para cuevas visibles.",
  },
  {
    group: "lumen",
    name: "Reflejos Lumen",
    off: "r.Lumen.Reflections.Allow 0",
    on: "r.Lumen.Reflections.Allow 1",
    quita: "Quita reflejos Lumen (FPS). El mundo sigue viéndose.",
    pone: "Pone reflejos Lumen (caros).",
  },
  {
    group: "lumen",
    name: "Contraste reflejos Lumen",
    off: "r.Lumen.Reflections.Contrast 0",
    on: "r.Lumen.Reflections.Contrast 1",
    quita: "Baja contraste de reflejos (menos plástico / brillo raro).",
    pone: "Contraste de reflejos normal.",
  },
  {
    group: "lumen",
    name: "Lumen hardware RT",
    off: "r.Lumen.HardwareRayTracing 0",
    on: "r.Lumen.HardwareRayTracing 1",
    quita: "Quita ray tracing de Lumen (si tu GPU lo usa).",
    pone: "Intenta RT por hardware (depende de la GPU).",
  },
  {
    group: "lumen",
    name: "Lumen probe resolution",
    off: "r.Lumen.ScreenProbeGather.RadianceCache.ProbeResolution 16",
    on: "r.Lumen.ScreenProbeGather.RadianceCache.ProbeResolution 32",
    quita: "Baja calidad de probes Lumen (más FPS, GI más sucio).",
    pone: "Probes más finos (más caro).",
  },
  {
    group: "lumen",
    name: "Lumen screen traces",
    off: "r.Lumen.ScreenProbeGather.ScreenTraces 0",
    on: "r.Lumen.ScreenProbeGather.ScreenTraces 1",
    quita: "Quita screen traces de Lumen (un poco más FPS).",
    pone: "Screen traces ON.",
  },
  {
    group: "lumen",
    name: "Calidad GI (sg)",
    off: "sg.GlobalIlluminationQuality 0",
    on: "sg.GlobalIlluminationQuality 3",
    quita: "Tira GI al mínimo (scalability).",
    pone: "GI alto.",
  },
  {
    group: "hierba",
    name: "Hierba (enable)",
    off: "grass.Enable 0",
    on: "grass.Enable 1",
    quita: "Apaga hierba. Mucho FPS y más visibilidad.",
    pone: "Enciende hierba.",
  },
  {
    group: "hierba",
    name: "Tamaño hierba",
    off: "grass.SizeScale 0",
    on: "grass.SizeScale 1",
    quita: "Hierba a tamaño 0 (casi invisible aunque esté enable).",
    pone: "Tamaño normal.",
  },
  {
    group: "hierba",
    name: "Densidad hierba",
    off: "grass.DensityScale 0",
    on: "grass.DensityScale 1",
    quita: "Quita densidad de hierba.",
    pone: "Densidad normal.",
  },
  {
    group: "hierba",
    name: "Sombras dinámicas de hierba",
    off: "grass.DisableDynamicShadows 1",
    on: "grass.DisableDynamicShadows 0",
    quita: "La hierba no proyecta sombras (FPS).",
    pone: "Hierba con sombras.",
  },
  {
    group: "hierba",
    name: "Calidad foliage",
    off: "sg.FoliageQuality 0",
    on: "sg.FoliageQuality 3",
    quita: "Plantas/árboles al mínimo.",
    pone: "Foliage alto.",
  },
  {
    group: "hierba",
    name: "LOD foliage",
    off: "foliage.LODDistanceScale 0.5",
    on: "foliage.LODDistanceScale 1",
    quita: "Los árboles bajan de detalle más cerca (FPS).",
    pone: "LOD normal.",
  },
  {
    group: "hierba",
    name: "WPO foliage",
    off: "r.foliage.WPODisableMultiplier 1",
    on: "r.foliage.WPODisableMultiplier 0",
    quita: "Reduce movimiento World Position Offset de plantas.",
    pone: "Plantas con WPO (viento, más caro).",
  },
  {
    group: "agua",
    name: "Capa de agua",
    off: "r.Water.SingleLayer 0",
    on: "r.Water.SingleLayer 1",
    quita: "Quita/simplifica el agua (a veces se ve el fondo raro).",
    pone: "Agua single-layer ON (se ve el mar).",
  },
  {
    group: "agua",
    name: "Reflejos del agua",
    off: "r.Water.SingleLayer.Reflection 0",
    on: "r.Water.SingleLayer.Reflection 1",
    quita: "Quita reflejos del agua. FPS y menos brillo.",
    pone: "Reflejos en el agua.",
  },
  {
    group: "post",
    name: "Bloom",
    off: "r.BloomQuality 0",
    on: "r.BloomQuality 5",
    quita: "Quita el glow/bloom.",
    pone: "Bloom alto.",
  },
  {
    group: "post",
    name: "Depth of field",
    off: "r.DepthOfFieldQuality 0",
    on: "r.DepthOfFieldQuality 2",
    quita: "Quita desenfoque de fondo.",
    pone: "DOF ON.",
  },
  {
    group: "post",
    name: "Motion blur",
    off: "r.MotionBlur.Amount 0",
    on: "r.MotionBlur.Amount 0.5",
    quita: "Quita motion blur.",
    pone: "Motion blur.",
  },
  {
    group: "post",
    name: "Lens flare",
    off: "r.LensFlareQuality 0",
    on: "r.LensFlareQuality 2",
    quita: "Quita flares de lente.",
    pone: "Lens flares.",
  },
  {
    group: "post",
    name: "Eye adaptation",
    off: "r.EyeAdaptationQuality 0",
    on: "r.EyeAdaptationQuality 2",
    quita: "Quita auto-exposición (brillo más estable, a veces quemado).",
    pone: "Ojo se adapta a oscuro/claro.",
  },
  {
    group: "post",
    name: "Color grading",
    off: "r.Color.Grading 0",
    on: "r.Color.Grading 1",
    quita: "Quita LUT/color grading (colores más crudos).",
    pone: "Color grading del juego.",
  },
  {
    group: "post",
    name: "Materiales de postproceso",
    off: "r.PostProcessing.DisableMaterials 1",
    on: "r.PostProcessing.DisableMaterials 0",
    quita: "Desactiva materiales de PP (look más plano/plástico, FPS).",
    pone: "PP materials ON (look normal).",
  },
  {
    group: "post",
    name: "SSR (reflejos pantalla)",
    off: "r.SSR.Quality 0",
    on: "r.SSR.Quality 3",
    quita: "Quita screen-space reflections.",
    pone: "SSR de calidad.",
  },
  {
    group: "post",
    name: "AO overwrite scene color",
    off: "r.AOOverwriteSceneColor 0",
    on: "r.AOOverwriteSceneColor 1",
    quita: "No pinta AO encima del color de escena (look más limpio).",
    pone: "AO puede teñir la escena (a veces sucio).",
  },
  {
    group: "post",
    name: "Min roughness override",
    off: "r.MinRoughnessOverride 0",
    on: "r.MinRoughnessOverride 1",
    quita: "Materiales con roughness normal (no tan plástico).",
    pone: "Fuerza roughness mínimo (look más mate/plástico).",
  },
  {
    group: "post",
    name: "Calidad de materiales",
    off: "r.MaterialQualityLevel 0",
    on: "r.MaterialQualityLevel 1",
    quita: "Materiales low (más FPS, más feo).",
    pone: "Materiales normal.",
  },
  {
    group: "post",
    name: "Sharpen (nitidez)",
    off: "r.Tonemapper.Sharpen 0",
    on: "r.Tonemapper.Sharpen 2",
    quita: "Sin sharpen extra.",
    pone: "Afila la imagen (2–3 típico PvP).",
  },
  {
    group: "post",
    name: "Calidad tonemapper",
    off: "r.Tonemapper.Quality 0",
    on: "r.Tonemapper.Quality 5",
    quita: "Tonemapper barato.",
    pone: "Tonemapper de calidad.",
  },
  {
    group: "post",
    name: "Furnace test (sombreado raro)",
    off: "r.Shading.FurnaceTest 0",
    on: "r.Shading.FurnaceTest 1",
    quita: "Shading normal.",
    pone: "Test de shading (look extraño, no para jugar limpio).",
  },
  {
    group: "post",
    name: "Refracción",
    off: "r.RefractionQuality 0",
    on: "r.RefractionQuality 2",
    quita: "Quita refracción (cristales/agua menos caros).",
    pone: "Refracción ON.",
  },
  {
    group: "post",
    name: "Temporal AA",
    off: "r.TemporalAA 0",
    on: "r.TemporalAA 1",
    quita: "Quita TAA (más aliasing, imagen más cruda).",
    pone: "TAA ON (más suave, un pelín borroso).",
  },
  {
    group: "post",
    name: "Método de anti-aliasing",
    off: "r.AntiAliasingMethod 0",
    on: "r.AntiAliasingMethod 2",
    quita: "AA off (0). Más dientes de sierra, más nítido.",
    pone: "TAA (2) típico.",
  },
  {
    group: "fps",
    name: "VSync",
    off: "r.vsync 0",
    on: "r.vsync 1",
    quita: "VSync off. Menos input lag, tearing posible.",
    pone: "VSync on. Corta tearing, más delay.",
  },
  {
    group: "fps",
    name: "FPS cap",
    off: "t.MaxFPS 0",
    on: "t.MaxFPS 60",
    quita: "Sin límite de FPS (0).",
    pone: "Tope a 60 (o el número que pongas).",
  },
  {
    group: "fps",
    name: "Screen percentage",
    off: "r.ScreenPercentage 50",
    on: "r.ScreenPercentage 100",
    quita: "Renderiza al 50% y escala (mucho FPS, más borroso).",
    pone: "100% nativo.",
  },
  {
    group: "fps",
    name: "FSR3",
    off: "r.FidelityFX.FSR3.Enabled 0",
    on: "r.FidelityFX.FSR3.Enabled 1",
    quita: "Apaga FSR3.",
    pone: "Enciende FSR3 (upscale AMD).",
  },
  {
    group: "fps",
    name: "FSR3 DX12 nativo",
    off: "r.FidelityFX.FSR3.UseNativeDX12 0",
    on: "r.FidelityFX.FSR3.UseNativeDX12 1",
    quita: "FSR3 sin path nativo DX12.",
    pone: "FSR3 con DX12 nativo.",
  },
  {
    group: "fps",
    name: "Light culling",
    off: "r.LightCulling.Quality 0",
    on: "r.LightCulling.Quality 1",
    quita: "Culling de luces barato.",
    pone: "Culling de luces de más calidad.",
  },
  {
    group: "fps",
    name: "Detail mode",
    off: "r.DetailMode 0",
    on: "r.DetailMode 2",
    quita: "Menos meshes de detalle.",
    pone: "Detalle alto.",
  },
  {
    group: "fps",
    name: "HLOD mundo",
    off: "wp.Runtime.HLOD 0",
    on: "wp.Runtime.HLOD 1",
    quita: "Apaga HLODs (a veces más pop-in, a veces más FPS).",
    pone: "HLOD ON (lejos se ve un mesh combinado).",
  },
  {
    group: "fps",
    name: "Forzar disable HLOD",
    off: "wp.Runtime.HLOD.ForceDisable 1",
    on: "wp.Runtime.HLOD.ForceDisable 0",
    quita: "Fuerza HLOD off.",
    pone: "No fuerza el disable.",
  },
  {
    group: "fps",
    name: "Near clip plane",
    off: "r.SetNearClipPlane 10",
    on: "r.SetNearClipPlane 10",
    quita: "10 = no te clipea tanto la cámara en walls cercanas. 0 es más agresivo.",
    pone: "Mismo cvar; 10 es el valor jugable típico.",
  },
  {
    group: "fps",
    name: "Ángulo mínimo luz direccional",
    off: "r.GlobalMinDirectionalLightAngle 0",
    on: "r.GlobalMinDirectionalLightAngle 0",
    quita: "0 = luz de sol normal. 200 (en algunos presets) aplana la luz.",
    pone: "Valor 0 recomendado para look limpio.",
  },
  {
    group: "fps",
    name: "Early Z pass",
    off: "r.EarlyZPass 0",
    on: "r.EarlyZPass 1",
    quita: "Salta early-Z (puede subir o bajar FPS según GPU).",
    pone: "Early-Z ON.",
  },
  {
    group: "texturas",
    name: "Calidad texturas (sg)",
    off: "sg.TextureQuality 0",
    on: "sg.TextureQuality 3",
    quita: "Texturas low.",
    pone: "Texturas high.",
  },
  {
    group: "texturas",
    name: "Streaming pool",
    off: "r.Streaming.PoolSize 3000",
    on: "r.Streaming.PoolSize 4000",
    quita: "Pool pequeño = texturas borrosas / más VRAM libre. 1 o 0 es extremo.",
    pone: "Pool grande = texturas nítidas, más VRAM.",
  },
  {
    group: "texturas",
    name: "Mip bias",
    off: "r.MipMapLODBias 0",
    on: "r.MipMapLODBias 0",
    quita: "0 = nitidez normal. 1+ = texturas más blur (FPS).",
    pone: "0 recomendado para no ver todo borroso.",
  },
  {
    group: "texturas",
    name: "Anisotropía",
    off: "r.MaxAnisotropy 0",
    on: "r.MaxAnisotropy 8",
    quita: "Sin filtro aniso (texturas de suelo feas de lado).",
    pone: "8x / 16x nítido en ángulos.",
  },
  {
    group: "texturas",
    name: "Texture streaming",
    off: "r.TextureStreaming 0",
    on: "r.TextureStreaming 1",
    quita: "Intenta cargar texturas sin streaming (puede stutter / VRAM).",
    pone: "Streaming ON (lo normal).",
  },
  {
    group: "texturas",
    name: "Virtual textures feedback",
    off: "r.VT.EnableFeedback 0",
    on: "r.VT.EnableFeedback 1",
    quita: "Quita feedback de virtual textures.",
    pone: "VT feedback ON.",
  },
  {
    group: "texturas",
    name: "VT pool scale",
    off: "r.VT.PoolSizeScale 0",
    on: "r.VT.PoolSizeScale 1",
    quita: "Pool VT mínimo.",
    pone: "Pool VT normal.",
  },
  {
    group: "texturas",
    name: "Nanite pixels per edge",
    off: "r.Nanite.MaxPixelsPerEdge 2",
    on: "r.Nanite.MaxPixelsPerEdge 1",
    quita: "Nanite más agresivo (2–3 = menos densos, más FPS).",
    pone: "1 = Nanite más detallado (más caro).",
  },
  {
    group: "fx",
    name: "Partículas CPU",
    off: "FX.MaxCPUParticlesPerEmitter 0",
    on: "FX.MaxCPUParticlesPerEmitter 100",
    quita: "Casi sin partículas CPU (humo/explosiones más vacíos, FPS).",
    pone: "Partículas CPU normales.",
  },
  {
    group: "fx",
    name: "Niagara GPU spawn",
    off: "fx.MaxNiagaraGPUParticlesSpawnPerFrame 0",
    on: "fx.MaxNiagaraGPUParticlesSpawnPerFrame 10000",
    quita: "Corta spawn Niagara GPU.",
    pone: "Niagara GPU normal.",
  },
  {
    group: "fx",
    name: "Niagara sprites",
    off: "fx.EnableNiagaraSpriteRendering 0",
    on: "fx.EnableNiagaraSpriteRendering 1",
    quita: "Apaga sprites Niagara.",
    pone: "Sprites Niagara ON.",
  },
  {
    group: "fx",
    name: "GPU particles",
    off: "fxAllowGPUParticles 0",
    on: "fxAllowGPUParticles 1",
    quita: "Apaga partículas GPU.",
    pone: "Partículas GPU ON.",
  },
  {
    group: "fx",
    name: "Calidad efectos",
    off: "sg.EffectsQuality 0",
    on: "sg.EffectsQuality 3",
    quita: "Efectos low.",
    pone: "Efectos high.",
  },
  {
    group: "fx",
    name: "Meshes destruidos",
    off: "ark.MaxActiveDestroyedMeshGeoCollectionCount 0",
    on: "ark.MaxActiveDestroyedMeshGeoCollectionCount 10",
    quita: "No deja geo de estructuras rotas (limpia combates, FPS).",
    pone: "Deja restos de destrucción.",
  },
  {
    group: "show",
    name: "Instanced foliage",
    off: "show InstancedFoliage",
    on: "show InstancedFoliage",
    toggle: true,
    quita: "TOGGLE. Esconde/enseña foliage instanciado. Si lo tiras 2 veces se cancela.",
    pone: "Mismo comando: es un interruptor, no tiene 0/1.",
  },
  {
    group: "show",
    name: "Instanced grass",
    off: "show InstancedGrass",
    on: "show InstancedGrass",
    toggle: true,
    quita: "TOGGLE. Esconde/enseña hierba instanciada. Dos veces = se deshace.",
    pone: "Mismo comando (toggle).",
  },
  {
    group: "show",
    name: "Instanced static meshes",
    off: "show InstancedStaticMeshes",
    on: "show InstancedStaticMeshes",
    toggle: true,
    quita: "TOGGLE. Afecta meshes instanciadas (a veces teslas/turrets/props). Dos veces se cancela. No lo metas dos veces en el mismo exec.",
    pone: "Mismo comando (toggle).",
  },
  {
    group: "show",
    name: "Dynamic shadows",
    off: "show DynamicShadows",
    on: "show DynamicShadows",
    toggle: true,
    quita: "TOGGLE. Esconde/enseña sombras dinámicas.",
    pone: "Mismo comando (toggle).",
  },
  {
    group: "camara",
    name: "FOV (consola)",
    off: "fov 90",
    on: "fov 170",
    quita: "FOV estrecho. El permanente es la pestaña FOV (170 en el menú = FOVMultiplier 1.70).",
    pone: "fov 170 en consola. El del menú se guarda en GameUserSettings.ini.",
  },
  {
    group: "camara",
    name: "Scroll del inventario",
    off: "Slate.GlobalScrollAmount 80",
    on: "Slate.GlobalScrollAmount 20",
    quita: "Scroll más rápido (80–120) en menús.",
    pone: "Scroll lento/preciso (20).",
  },
  {
    group: "camara",
    name: "Tamaño iconos",
    off: "ark.MinIconSize 0.1",
    on: "ark.MinIconSize 1",
    quita: "Iconos más pequeños en HUD.",
    pone: "Iconos tamaño normal.",
  },
  {
    group: "debug",
    name: "Contador FPS",
    off: "stat fps",
    on: "stat fps",
    toggle: true,
    quita: "TOGGLE. Enciende/apaga el FPS en pantalla.",
    pone: "Mismo comando.",
  },
  {
    group: "debug",
    name: "stat unit",
    off: "stat unit",
    on: "stat unit",
    toggle: true,
    quita: "TOGGLE. Muestra Game/Draw/GPU ms (dónde te come el frame).",
    pone: "Mismo comando.",
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { GROUPS, COMMANDS };
}
if (typeof window !== "undefined") {
  window.PABLO_GROUPS = GROUPS;
  window.PABLO_COMMANDS = COMMANDS;
}
