name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: npm run publish -- -c.publish.owner=${{ github.repository_owner }} -c.publish.repo=${{ github.event.repository.name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
